cruise-automation/isopod

- pkg/runtime/runtime.go
Fixes https://github.com/cruise-automation/isopod/issues/8
> runtime: error if no addon matches the filter regexp

- pkg/util/json.go
Without this, doing something like:
```
kube.get(
deployment="kube-system/kube-dns",
api_group="extensions",
json=True,
)
```
fails with `unsupported JSON data type: int64`.
> Add int64 json support

- pkg/kube/kube_fake.go
Adds MutatingWebhookConfigurations to kube-fake to enable testing of these resources.
Signed-off-by: dustin-decker <dustin.decker@getcruise.com>
> Enable testing MutatingWebhookConfigurations

- pkg/vault/vault.go
- prevents writing Vault token during vault.write() dry run
- returns response from Vault write, if there is one (such as when writing to a PKI backend role)
> Improve vault write

- pkg/runtime/options.go
- pkg/vault/vault.go
- pkg/vault/vault_fake.go
- pkg/vault/vault_test.go
- Uses Vault fake for dry runs
- Fall back to real Vault contents if fake key does not exist
- Adds PKI backend support for certificate issuance to vault_fake
- Uses Vault fake for unit tests. It had some other fake before.
Signed-off-by: dustin-decker <dustin.decker@getcruise.com>
> Improve Vault dry run and fake

- README.md
- pkg/cloud/gke/auth.go
- pkg/cloud/gke/gke.go
verified it's working for both regular cluster and only private network cluster
```
./install.sh -c cluster=paas-ci-us-central1-4
cluster.Endpoint 10.212.1.178
Beginning rollout [rollout-bnkktobo6hijflfj2aag] installation...
...
Rollout [rollout-bnkktobo6hijflfj2aag] is live!
```
```
/install.sh -c cluster=paas-dev-us-central1 --dry_run -m rbacsync
Beginning rollout [rollout-bnknk6jo6hinkp3kpei0] installation...
I1205 13:43:55.155076   31332 properties.go:196] proto: tag has too few fields: "-"
*** secret.v1 `secret.v1 `kube-system/rbacsync-gsuite-credentials'' ***
--- live
+++ head
@@ -5,10 +5,10 @@
```
> auth with private master endpoint if existed

- pkg/vault/vault.go
- pkg/vault/vault_test.go
With some `vault.write()` requests we need to write lists for the values of keyword arguments.
For example, such as with [CSR roles](https://www.vaultproject.io/api-docs/secret/pki/#parameters-8).
```
vault.write(pki/roles/example-dot-com, allowed_domains="my-website.com",
allow_subdomains="true", max_ttl="72h",
key_usage=["DigitalSignature", "KeyAgreement", "KeyEncipherment"])
```
> Support writing list values in vault.write

- README.md
- pkg/cloud/onprem/onprem.go
- pkg/cloud/onprem/onprem_test.go
- pkg/runtime/runtime.go
- pkg/vault/vault.go
Adding the ability to use kubeconfigs that exist in vault. This allows the onprem type to not just use local kubeconfigs.
Also adding a cluster name output so that we can see which cluster is getting changes applied.
cc @cxuu
> adding vault kubeconfig for onprem

- pkg/kube/diff.go
- pkg/runtime/runtime.go
and a bug fix where the following cases will result in nil pointer dereference
* deploying a new k8s object for the first time (live is nil)
* removing a k8s object (head is nil)
> runtime: do not create a rollout for dryrun

- pkg/kube/kube.go
Without this fix, the dry run diff output looks like 
```
*** namespace.v1 `namespace.v1 `ingress'' ***
```
but we want 
```
*** namespace.v1 `ingress' ***
```
This issue currently only exist for `kube.put()`. `kube.put_yaml()` and `helm.apply()` works fine
> diff: clean resource name

- main.go
- pkg/kpath/kpath.go
- pkg/kpath/kpath_test.go
- pkg/kube/filter.go
- pkg/modules/base64.go
- pkg/modules/base64_test.go
- pkg/modules/dict.go
- pkg/modules/http_test.go
- pkg/modules/struct_test.go
- pkg/modules/uuid.go
- pkg/modules/uuid_test.go
- pkg/runtime/runtime.go
- pkg/util/filter_file.go
- pkg/util/filter_file_test.go
- pkg/util/strings_flag.go
Update: this PR now redirect stdlog to verbose glog instead of filtering through pipe. Also, I added the license preamble to files without it.
Original Description:
Some third-party lib that we use would write to stderr (using Go's standard `log` package)
```
I0318 18:23:41.979510   33487 clone.go:234] proto: don't know how to copy 0
```
or 
```
I0318 18:23:24.030427   33487 properties.go:196] proto: tag has too few fields: "-"
```
and is very distracting. 
Before this PR, Isopod does filter these log spam in actual addon install but not in dryrun. Prior implementation also has to wait until addon installation is complete before filtering the captured log. In this PR, such filtering/editing is done in streams and works for both dry run and actual install.
> diff: filter log spam in dryrun

- .circleci/config.yml
- main.go
- pkg/cloud/cloud.go
- pkg/kube/kube.go
- pkg/kube/kube_fake.go
- pkg/kube/kube_test.go
- pkg/kube/kube_yaml.go
- pkg/modules/struct_test.go
- pkg/modules/uuid_test.go
- pkg/runtime/config.go
- pkg/runtime/options.go
- pkg/runtime/runtime.go
- pkg/runtime/runtime_test.go
- pkg/runtime/unittest.go
This implementation adds the feature of life cycle management for
immutable resources. When a request to update an immutable resource is
sent, we return an error. If the -force flag is set when running
the binary, the immutable resource is going to be deleted and recreated.
The dry run behavior reflects this update and returns an error if an
immutable resource should be updated or writes a warning if the -force
flag is enabled
Signed-off-by: Jonny Langefeld <jonny.langefeld@getcruise.com>
> Implement deletaion and recreation of immutable resources

- README.md
- pkg/kube/kube.go
- pkg/kube/kube_test.go
This commit adds the ability to receive a list return in starlark, if the kubernetes api return a ListInterface.
This is useful for queries for a list of pods or deployments.
* tests written
* documentation update
> Add list returns

- main.go
Through the version updated introduced in https://github.com/cruise-automation/isopod/pull/39 we picked up an upgrade of the k8s/client-go library. Somwhere inbetween the [two versions of the change](https://github.com/cruise-automation/isopod/compare/v1.1.2...v1.1.3\#diff-37aff102a57d3d7b797f152915a6dc16L119-R109) k8s/client-go introduced an advanced rate limiter, that [assumes default qps of 5 and burst of 10](https://github.com/kubernetes/client-go/blob/master/rest/config.go\#L114-L120). For the requests that isopod makes these assumptions are too low and result in frequent throttling request errors.
This fix introduces higher defaults. To replicate the behavior of isopod v1.1.2, we could also swtich off rate limiting entirely by setting `kubeC.QPS = float32(-1)`, but now that we have …
> Fix throttling requests

- pkg/kube/kube.go
- pkg/kube/kube_fake.go
- pkg/runtime/unittest.go
Previously the Deployment resource is registered in the kube_fake's discovery client under two API groups: `apps/v1` and `extensions/v1beta1`. Apparently, this leads to non-deterministic GVK inference from RESTMapper (https://github.com/cruise-automation/isopod/blob/master/pkg/kube/api.go#L59-L74). 
The result is that `kube.get(deployment="ns/myapp")` maybe either of
```
GET /apis/apps/v1/namespaces/NS/deployments/myapp
```
or
```
GET /apis/extensions/v1beta1/namespaces/NS/deployments/myapp
```
but in the latter case, kube fake will return empty results (and fail the Starlark unit tests), because most users use the `k8s.io.api.apps.v1` proto package to build a Deployment.
> fix: app/v1 api group in kube fake

- pkg/runtime/generate.go
- pkg/runtime/testdata/deployment.ipd
- pkg/runtime/testdata/deployment.json
Starlark structs go by the proto tags and not by json tags.
In fact, sometimes the json tags arent set, like in the example of liveness probe.
This fix gets the name from the proto tag to account for that
Fix #53
> Get names from proto tags instead of json tags

- pkg/runtime/generate.go
- pkg/runtime/testdata/custom-resource.ipd
- pkg/runtime/testdata/multiple.ipd
This commit improves the rendering of unknown resources and creates a [Starlark struct](https://docs.bazel.build/versions/master/skylark/lib/struct.html) instead of just a json string.
Fix #51
> Render custom resources as Starlark structs

- pkg/runtime/generate.go
- pkg/runtime/generate_test.go
- pkg/runtime/testdata/dir.ipd
This commit adds support for directories as input. The output will be one single isopod addon file.
Fix #48
> Support input directories for Starlark code generator

- pkg/runtime/generate.go
- pkg/runtime/testdata/clusterrolebinding.ipd
- pkg/runtime/testdata/dir.ipd
- pkg/runtime/testdata/multiple.ipd
apiGroup was filtered out, but is needed for instance in the case of roleRef
> Fix apiGroup

- go.mod
- go.sum
- pkg/store/kube/store.go
- vendor/github.com/dustin/go-humanize/.travis.yml
- vendor/github.com/dustin/go-humanize/LICENSE
- vendor/github.com/dustin/go-humanize/README.markdown
- vendor/github.com/dustin/go-humanize/big.go
- vendor/github.com/dustin/go-humanize/bigbytes.go
- vendor/github.com/dustin/go-humanize/bytes.go
- vendor/github.com/dustin/go-humanize/comma.go
- vendor/github.com/dustin/go-humanize/commaf.go
- vendor/github.com/dustin/go-humanize/ftoa.go
- vendor/github.com/dustin/go-humanize/humanize.go
- vendor/github.com/dustin/go-humanize/number.go
- vendor/github.com/dustin/go-humanize/ordinals.go
- vendor/github.com/dustin/go-humanize/si.go
- vendor/github.com/dustin/go-humanize/times.go
- vendor/modules.txt
isopod stores every applied addon as configmap for auditing. However for
large addons an error was thrown, because the max size of a configmap
is limited by [etcd to 1MB](https://etcd.io/docs/v3.2.17/dev-guide/limit/#:~:text=1MB%20of,%20data.)
This fix catches the error and gives the user notice that the configmap
couldn't be stored, but the rollout is still live.
Example output:
```
$ isopod --context cluster=kind-kind
-kubeconfig=/tmp/kind-kubeconfig install $(pwd)/local/testenv/main.ipd
Current cluster: ("kind-kind")
Beginning rollout [rollout-bs7hc9p8d3b6d3h91ou0] installation...
Installing kafka... done
Addon not stored in configmap because it is larger than the maximum of 1 MB ( 1.9 MB )
Rollout [rollout-bs7hc9p8d3b6d3h91ou0] is live!
```
Fix #65
> Fix configmap too large error

- pkg/runtime/generate.go
- pkg/runtime/testdata/clusterrolebinding.ipd
- pkg/runtime/testdata/crd.ipd
- pkg/runtime/testdata/deployment.ipd
- pkg/runtime/testdata/dir.ipd
- pkg/runtime/testdata/multiple.ipd
- pkg/runtime/testdata/validating-webhook.ipd
This fix changes the current code genertation from
```
blah_blah=[foobar(
something,
),
foobar(
something_else,
)]
```
to
```
blah_blah=[
foobar(
something,
),
foobar(
something_else,
),
]
```
Fix #68
> Clean up indentation for code generator

- pkg/addon/addon.go
- pkg/loader/loader.go
- pkg/runtime/runtime.go
This PR functions as a review for the `tagging_versioned_resources` branch and gives recommendations for code simplifications.
* it removes the duplicated parsing logic in the install command and just saves the addons with the full path in the cache. That way it can be referred to later using a.filepath
> Recommendation for small code improvements

- pkg/kube/kube_fake.go
Error seen without this:
```
[2020-09-09T20:13:57Z] <kube.put>: failed to map resource: no matches for kind "APIService" in version 
"apiregistration.k8s.io/v1beta1"
[2020-09-09T20:13:58Z] <kube.put>: failed to map resource: no matches for kind "PriorityClass" in version 
"scheduling.k8s.io/v1beta1"
```
> Testing support for PriorityClass and APIService resources

- pkg/loader/loader.go
- Nested load was broken in previous version tagging commit: https://github.com/cruise-automation/isopod/commit/f2c477679e32f05f9646f6d178d07e166f20435b#diff-7ebb5f642faf323b147d718da7f18576L129-R142
This change meant that these two vars which relied on the "modified" value of `module`
Were now using the "unmodified" value of `module` and running the addons threw this error:
```
E0910 16:04:54.169410   17535 main.go:274] addons run failed: <addon: my_addon> load failed: cannot load my_addon/my_addon.ipd: lstat /private/tmp/isopod-workspace/versioned_addon/1.0.0/@versioned_addon: no such file or directory
```
> Fix load command inside a versioned addon

- pkg/kube/kube_fake.go
K8S 1.16 has support for CronJobs only in BatchV1Beta1 API Group:
https://v1-16.docs.kubernetes.io/docs/reference/generated/kubernetes-api/v1.16/#cronjob-v1beta1-batch
> Cronjobs Batch V1Beta1 support

- pkg/kube/kube_fake.go
Fixes kube_fake unable to query for CronJob objects
> Fix CronJob under wrong namespace

- main.go
- pkg/vault/vault_fake.go
During a Dry Run we can't do a list on these paths:
```
E1006 10:19:23.320032   13387 main.go:274] addons run failed: `install' execution failed: failed addon installation: <addon: addon> run failed: <vault.read>: request failed: Error making API request.
URL: GET https://vault.abc.xyz:8200/v1/sys/?list=true
Code: 403. Errors:
* 1 error occurred:
* permission denied
vault list sys
No value found at sys/
```
Also fixing flag.Parse error:
```
ERROR: logging before flag.Parse: I1021 14:45:20.344276   70669 main.go:73] Using no remote modules
```
> Allow read of non-secret paths

- main.go
Currently the return means the binary won't work unless `--deps` is specified
> Fix error in default deps func

- go.mod
- pkg/addon/addon.go
- pkg/runtime/runtime.go
- pkg/runtime/unittest.go
- pkg/util/errors.go
- pkg/util/errors_test.go
- vendor/modules.txt
This PR makes CLI print starlark runtime error with full stacktrace.
Currnelty the CLI prints runtime errors like this, now way to tell where the error is from:
```
> isopod test /Users/mingfei.huang/workspace/paas-addon-common-bundle/addons/istio
invalid call of non-function (string)
FAIL	/Users/mingfei.huang/workspace/paas-addon-common-bundle/addons/istio/cert_update_test.ipd
```
With this PR:
```
> go run . test /Users/mingfei.huang/workspace/paas-addon-common-bundle/addons/istio
Traceback (most recent call last):
/Users/mingfei.huang/workspace/paas-addon-common-bundle/addons/istio/cert_update_test.ipd:8:24: in test_install_cert_update
./cert_update.ipd:24:17: in install_cert_update
./cert_update.ipd:122:7: in install_cron
Error: invalid call of non-function (string)
FAIL …
```
> Print stacktrace for runtime errors

- pkg/kube/scheme.go
This support is required to create a CRD that uses apiextensionsv1
> Scheme support for apiextensionsv1

- README.md
- pkg/kube/api.go
- pkg/kube/api_test.go
- testdata/api_group_test.ipd
This proposes to pass in api version as postfix of the `api_group` parameter for `kube.get` and `kube.delete`. It's used for identifying objects when more than 1 version of an API resource is registered to `kube_fake` at runtime.
Example usage:
```python
kube.get(customresourcedefinition="crd-v1", api_group="apiextensions.k8s.io/v1", wait="0s")
```
This does not break backward compatibility, `api_group` can still be used without version.
Added a tests:
* unit test for `newResource` function, for resource version resolution
* integration test `api_group_test.ipd`
> Encode version in api_group

- main.go
- pkg/runtime/runtime_test.go
- pkg/store/noopstore.go
- pkg/store/noopstore_test.go
This PR adds a `NoopStore` implementation of the `store.Store` interface. This lets isopod run without creating configmaps on every run in case the rollout information is stored entirely externally to isopod or is otherwise unneeded.
The original behaviour is preserved as the default, and an additional `--no_store` flag is added to swap to the NoopStore.
> Add Noop Store
